### ISSUE TITLE
在运行campux容器的步骤中出错且重启后无任何日志

### ISSUE THREAD

**Issue by xxdoggie** [RockChinQ/Campux#15]
panic: 请修改配置文件

goroutine 1 [running]:
main.main()
/home/runner/work/Campux/Campux/main.go:26 +0x71
panic: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: localhost:27017, Type: Unknown, Last error: dial tcp [::1]:27017: connect: connection refused }, ] }

goroutine 1 [running]:
github.com/RockChinQ/Campux/backend/database.NewMongoDBManager()
/home/runner/work/Campux/Campux/backend/database/mongo.go:88 +0x285
github.com/RockChinQ/Campux/backend/core.NewApplication()
/home/runner/work/Campux/Campux/backend/core/app.go:21 +0x25
main.main()
/home/runner/work/Campux/Campux/main.go:30 +0x45

**Comment by RockChinQ** [comment]
不是容器的话，你得自己解决一下外部组件的地址问题。这里你给MongoDB配置的地址是localhost:27017 确定一下从运行main.go的主机能不能正常访问这个MongoDB地址，或者更换正确的地址。
