### ISSUE TITLE
搭配NapNeko使用时出现“cookies过期”误报的现象

### ISSUE THREAD

**Issue by Gao-Siqi** [RockChinQ/Campux#39]
如图，群中提示cookies失效，但是可以正常投稿
附上Campux容器日志
[log.txt](https://github.com/user-attachments/files/17444522/log.txt)
![微信图片_20241019171801](https://github.com/user-attachments/assets/dab657fe-7596-4644-a443-18be31fe40c2)

NapNeko容器日志未见明显报错，故未附上日志

**Comment by RockChinQ** [comment]
是 群内提示 “Cookies过期“但是 稿件可以发表到 QQ 空间 是吗？

**Comment by Gao-Siqi** [comment]
是的，不影响正常使用但是容易误导第一次配置的小白

**Comment by RockChinQ** [comment]
我这没遇到持续误报情况。

**Comment by RockChinQ** [comment]
有捕捉到一次这个问题，可以重新登录一下，或者忽略提醒
